### PR TITLE
Update spine-c and expand README

### PR DESCRIPTION
**Pull request by mjtorn**

### CODE REVIEW

**Comment by Geequlim** [comment]
I will test it later :)
Thanks!

**Comment by arthurtemple** [comment]
Looks great overall.

This PR, however, seems to be tackling several issues:
- spine-c version bump
- README cleanup
- API compatibility with Godot Animation API

Would it be possible to split the PR according to these specific goals?
This way it would be easier to analyse, test and discuss your diffs.

**Comment by mjtorn** [comment]
@thorthur that's how I'd usually do it but this project looked dead enough that I just threw this at it. At least it'snot all in one commit ;)

I don't have a good moment for it and @Geequlim being the head honcho, I would actually like to hear it from an authority before tearing it apart. But I will if it has to come to that.

**Comment by Geequlim** [comment]
@mjtorn  It can be compiled with you code but I can't load a spine resource with version `3.6.32`. Do you know where I can find out the examples with the version `3.6.52.1` ?

@thorthur  That is fine with diffrent commits in same PR :)

**Comment by mjtorn** [comment]
On Mon, Apr 23, 2018 at 07:30:31PM -0700, Geequlim wrote:
>@mjtorn  It can be compiled with you code but I can't load a spine resource
>with version `3.6.32`. Do you know where I can find out the examples with the
>version `3.6.52.1` ?

I bought the Essential license and tested with that. The documentation for
Spine says it would work for all 3.6 resources, so I'm thoroughly confused.

Did I understand correctly that you exported with 3.6.32 and it didn't work?

Is it possible for me to downgrade Spine? The documentation and empirical
evidence says it keeps itself up to date so that might be hard...

**Comment by Geequlim** [comment]
@mjtorn  I download the examples from https://github.com/EsotericSoftware/spine-runtimes and it doesn't work.

**Comment by mjtorn** [comment]
@Geequlim still WFM.

Origin commit EsotericSoftware/spine-runtimes@7e910cb8f7e2a266d5c072b55a726a02c30e39de which is new enough because the only changes since have been to Unity.

Copied the Spineboy example over.

Created symlinks `spineboy.atlas -> spineboy-ess.atlas` and `spineboy.atlas -> spineboy-pro.atlas`.

Tested the following:

  * spineboy-ess.json
  * spineboy-ess.skel
  * spineboy-pro.json
  * spineboy-pro.skel

They all work.

Do you have any information on why this would not work?

```bash
$ sha256sum *
95004a74ae64930cbabd0d0747d22bd5f120713fd2de6995031e5164daa15d03  spineboy-ess.atlas
038eb0375d86288f7fe57ede68d552ff0d8e095a3680ced1c27ff380568d58e4  spineboy-ess.json
01df9c33f752a996af6898d5372480ea7a50f68a505727a38dd1befcfd065264  spineboy-ess.skel
3dd7b10a0b6d242f7671eff9877ed1dbc0316ec02a12f92abca09c03d043814c  spineboy-pma.atlas
73fbe12e5f3f925582ced7ca36b34526425f90f4d1457b40b4f7d1c1282d0d81  spineboy-pma.png
586fdbb98791906d55a0a0dde911c7d64c6411f88e1319c3ba9bddbc5b4456c4  spineboy-pma.png.import
95004a74ae64930cbabd0d0747d22bd5f120713fd2de6995031e5164daa15d03  spineboy-pro.atlas
2cdf14329fe673b91db39322263a1cedaad837453a040f4d48003d20b15296f0  spineboy-pro.json
7bab49a9788afe84cb40c189660c33d5457dcfaa7b8670805209abf2de425489  spineboy-pro.skel
95004a74ae64930cbabd0d0747d22bd5f120713fd2de6995031e5164daa15d03  spineboy.atlas
e59b891bd9f2bdeb5aca2f95b05797a3c2d4f4af335c5ba8ec38359686c031d1  spineboy.png
8074f31134fdfd7260b17010ce6e95aa9eab723b0796b17ded651ca4261fbd08  spineboy.png.import
```

**Comment by Geequlim** [comment]
I forgot to rename the spine file name to the same as the atlas name.

**Comment by Geequlim** [comment]
It works fine with 3.0.3 rc.
I'm merging this PR thanks.

**Pull request merged**
